# Use lightweight Python base image
FROM python:3.10-slim-bookworm AS builder

# Set work directory
WORKDIR /app

# Install system dependencies required only for pip
RUN apt-get update && apt-get install -y --no-install-recommends \
        gcc \
    && rm -rf /var/lib/apt/lists/*

# Copy requirements first (better caching)
COPY frontend-requirements.txt .

# Install Python packages
RUN pip install --no-cache-dir -r frontend-requirements.txt

# Copy the rest of the app
COPY . .

# Streamlit will use backend URL from environment variable set in docker-compose
ENV BACKEND_URL=$BACKEND_URL

# Expose Streamlit default port
EXPOSE 8501

# Run Streamlit app
CMD ["streamlit", "run", "app.py", "--server.port=8501", "--server.address=0.0.0.0"]
